version: "3.4"

services:
  contact.api:
    container_name: directoryapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8000:80"

  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=master
    restart: always
    ports:
      - "5050:80"

  contactdb:
    container_name: directorydb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=master
      - POSTGRES_DB=DirectoryDb
    restart: always
    ports:
      - "5432:5432"
